name: Actions workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple go actions
        uses: actions/setup-go@v3.2.0
        with: 
          go-version: "1.18.3"
      - name: Check version of go
        run: go version
